/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealer;

import cardealer.database.CarsEntityFacade;
import cardealer.database.Database;
import cardealer.database.exceptions.EntityExistsException;
import cardealer.models.Car;
import cardealer.tableModels.CarTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.transaction.TransactionRequiredException;

/**
 *
 * @author ahmet
 */
public class CarForm extends javax.swing.JFrame {

    public static Database db;
    private Properties props;
    private static CarsEntityFacade cef;
    private static ArrayList<Car> mCars;
    private static Car currentCar;
    private static final Logger LOG = Logger.getLogger(CarForm.class.getName());
    private boolean carInsertFlag = false;

    /**
     * Creates new form Main
     */
    public CarForm() {
        initComponents();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        this.setTitle("Regjistrimi i veturave");
        jTblCars.setModel(new CarTableModel());
        try {
            Path workingDirectory = Paths.get("").toAbsolutePath();
            String path = workingDirectory + "\\build\\classes\\cardealer\\config\\config.ini";
            final String dir = System.getProperty("user.dir");

            File f = new File(path);
            if (f.exists()) {
                System.out.println("current dir = " + dir);
                props = new Properties();
                props.load(new FileInputStream(path));
                // TODO code application logic here
                System.out.println("Trying to connect");
                CarForm.db = new Database(props);
                System.out.println("Connected");
                cef = new CarsEntityFacade();
                mCars = new ArrayList<>();
                currentCar = new Car();
                populateCars();
                placeCars();
            }
        } catch (IOException | SQLException ex) {
            System.out.println(ex.getMessage());
        }

        jTblCars.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (jTblCars.getSelectedRowCount() == 1) {
                    jBtnCarEdit.setEnabled(true);
                } else {
                    jBtnCarEdit.setEnabled(false);
                }

            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
        this.pack();
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCars = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCarMake = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFCarManufacturingYear = new javax.swing.JTextField();
        jTFCarModel = new javax.swing.JTextField();
        jBtnCarCreate = new javax.swing.JButton();
        jBtnCarEdit = new javax.swing.JButton();
        jBtnCarSave = new javax.swing.JButton();
        jBtnRefresh = new javax.swing.JButton();
        jBtnCarCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblCars);

        jLabel1.setText("Bërja:");

        jTFCarMake.setEditable(false);
        jTFCarMake.setNextFocusableComponent(jTFCarModel);

        jLabel2.setText("Viti i prodhimit:");

        jLabel3.setText("Modeli:");

        jTFCarManufacturingYear.setEditable(false);
        jTFCarManufacturingYear.setNextFocusableComponent(jBtnCarCreate);

        jTFCarModel.setEditable(false);
        jTFCarModel.setNextFocusableComponent(jTFCarManufacturingYear);

        jBtnCarCreate.setText("Shto");
        jBtnCarCreate.setNextFocusableComponent(jBtnCarEdit);
        jBtnCarCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCarCreateActionPerformed(evt);
            }
        });

        jBtnCarEdit.setText("Redakto");
        jBtnCarEdit.setEnabled(false);
        jBtnCarEdit.setNextFocusableComponent(jBtnCarSave);
        jBtnCarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCarEditActionPerformed(evt);
            }
        });

        jBtnCarSave.setText("Ruaj");
        jBtnCarSave.setEnabled(false);
        jBtnCarSave.setNextFocusableComponent(jBtnRefresh);
        jBtnCarSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCarSaveActionPerformed(evt);
            }
        });

        jBtnRefresh.setText("Rifresko");
        jBtnRefresh.setNextFocusableComponent(jBtnCarCancel);
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });

        jBtnCarCancel.setText("Anulo");
        jBtnCarCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCarCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCarMake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCarModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCarManufacturingYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnCarCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnCarEdit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCarCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCarSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTFCarMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnCarCreate)
                            .addComponent(jBtnCarEdit)
                            .addComponent(jBtnCarSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnRefresh)
                            .addComponent(jBtnCarCancel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCarManufacturingYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCarCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCarCreateActionPerformed
        // TODO add your handling code here:
        clearCarFields();
        setCarFieldsEditable(true);
        carInsertFlag = true;
        jTFCarMake.requestFocus();
        jBtnCarCreate.setEnabled(false);
        jBtnCarSave.setEnabled(true);
    }//GEN-LAST:event_jBtnCarCreateActionPerformed

    private void jBtnCarEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCarEditActionPerformed
        // TODO add your handling code here:
        if (jTblCars.getSelectedRowCount() == 1) {
            int index = jTblCars.getSelectedRow();
            CarTableModel d = ((CarTableModel) jTblCars.getModel());
            currentCar = d.getSelectedRow(index);
            placeCarObjectToFields();
            setCarFieldsEditable(true);
            jBtnCarCreate.setEnabled(false);
            jBtnCarSave.setEnabled(true);
            jBtnCarEdit.setEnabled(false);
            carInsertFlag = false;
        }
    }//GEN-LAST:event_jBtnCarEditActionPerformed

    private void jBtnCarSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCarSaveActionPerformed
        // TODO add your handling code here:
        populateCarObject();
        boolean res = false;
        try {
            if (carInsertFlag) {
                res = cef.create(currentCar);

            } else {
                res = cef.update(currentCar);
            }
            setCarFieldsEditable(false);
            clearCarFields();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        if (res) {
            jBtnCarCreate.setEnabled(true);
            jBtnCarEdit.setEnabled(false);
            jBtnCarSave.setEnabled(false);
            populateCars();
            placeCars();

        }
    }//GEN-LAST:event_jBtnCarSaveActionPerformed

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        // TODO add your handling code here:
        populateCars();
        placeCars();
        jBtnCarCreate.setEnabled(true);
        jBtnCarEdit.setEnabled(false);
        jBtnCarSave.setEnabled(false);
        clearCarFields();
        setCarFieldsEditable(false);
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private void jBtnCarCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCarCancelActionPerformed
        jBtnCarCreate.setEnabled(true);
        jBtnCarEdit.setEnabled(false);
        jBtnCarSave.setEnabled(false);
        clearCarFields();
        setCarFieldsEditable(false);
    }//GEN-LAST:event_jBtnCarCancelActionPerformed

    private void clearCarFields() {
        this.jTFCarMake.setText("");
        this.jTFCarModel.setText("");
        this.jTFCarManufacturingYear.setText("");
    }

    private void setCarFieldsEditable(boolean flag) {
        this.jTFCarMake.setEditable(flag);
        this.jTFCarModel.setEditable(flag);
        this.jTFCarManufacturingYear.setEditable(flag);
    }

    private void placeCarObjectToFields() {
        this.jTFCarMake.setText(currentCar.getMake());
        this.jTFCarModel.setText(currentCar.getModel());
        this.jTFCarManufacturingYear.setText(currentCar.getManufacturingYear().toString());
    }

    private void populateCarObject() {
        currentCar.setMake(this.jTFCarMake.getText());
        currentCar.setModel(this.jTFCarModel.getText());
        currentCar.setManufacturingYear(Integer.parseInt(this.jTFCarManufacturingYear.getText()));
    }

    private void placeCars() {
        DefaultTableModel tableModel = (DefaultTableModel) jTblCars.getModel();
        tableModel.getDataVector().clear();
        Vector v = new Vector();
        for (Car c : mCars) {
            v = new Vector();
            v.add(c.getId());
            v.add(c.getMake());
            v.add(c.getModel());
            v.add(c.getManufacturingYear().toString());

            tableModel.addRow(v);

        }
        jTblCars.setModel(tableModel);
    }

    private static void populateCars() {
        try {
            mCars = cef.reads();

        } catch (EntityExistsException | IllegalStateException | IllegalArgumentException | TransactionRequiredException | SQLException ex) {
            Logger.getLogger(CarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCarCancel;
    private javax.swing.JButton jBtnCarCreate;
    private javax.swing.JButton jBtnCarEdit;
    private javax.swing.JButton jBtnCarSave;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCarMake;
    private javax.swing.JTextField jTFCarManufacturingYear;
    private javax.swing.JTextField jTFCarModel;
    private static javax.swing.JTable jTblCars;
    // End of variables declaration//GEN-END:variables
}
