/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealer;

import cardealer.database.GendersEntityFacade;
import cardealer.database.exceptions.EntityExistsException;
import cardealer.models.Gender;
import cardealer.tableModels.GenderTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.transaction.TransactionRequiredException;

/**
 *
 * @author ahmet
 */
public class GendersForm extends javax.swing.JFrame {

    private boolean genderInsertFlag;
    private Gender currentGender;
    private GendersEntityFacade gef;
    private ArrayList<Gender> mGenders;
    /**
     * Creates new form GendersForm
     */
    public GendersForm() {
        initComponents();
        currentGender = new Gender();
        gef = new GendersEntityFacade();
        mGenders = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaDescription = new javax.swing.JTextArea();
        jTfTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnGenderCreate = new javax.swing.JButton();
        jBtnGenderRefresh = new javax.swing.JButton();
        jBtnGenderCancel = new javax.swing.JButton();
        jBtnGenderEdit = new javax.swing.JButton();
        jBtnGenderSave = new javax.swing.JButton();
        jChkBStatus = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblGenders = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Emërtimi:");

        jTaDescription.setColumns(20);
        jTaDescription.setRows(5);
        jScrollPane2.setViewportView(jTaDescription);

        jLabel2.setText("Përshkrimi:");

        jBtnGenderCreate.setText("Shto");
        jBtnGenderCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenderCreateActionPerformed(evt);
            }
        });

        jBtnGenderRefresh.setText("Rifresko");
        jBtnGenderRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenderRefreshActionPerformed(evt);
            }
        });

        jBtnGenderCancel.setText("Anulo");
        jBtnGenderCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenderCancelActionPerformed(evt);
            }
        });

        jBtnGenderEdit.setText("Redakto");
        jBtnGenderEdit.setEnabled(false);
        jBtnGenderEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenderEditActionPerformed(evt);
            }
        });

        jBtnGenderSave.setText("Ruaj");
        jBtnGenderSave.setEnabled(false);
        jBtnGenderSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenderSaveActionPerformed(evt);
            }
        });

        jChkBStatus.setText("Po");

        jLabel3.setText("Statusi:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnGenderRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnGenderCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnGenderCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnGenderEdit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGenderSave)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkBStatus)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jTfTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBStatus)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGenderCreate)
                    .addComponent(jBtnGenderEdit)
                    .addComponent(jBtnGenderSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGenderRefresh)
                    .addComponent(jBtnGenderCancel))
                .addGap(102, 102, 102))
        );

        jTblGenders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblGenders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGenderCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenderCreateActionPerformed
        // TODO add your handling code here:
        clearGenderFields();
        setGenderFieldsEditable(true);
        genderInsertFlag = true;
        //jTFGenderMake.requestFocus();
        jBtnGenderCreate.setEnabled(false);
        jBtnGenderSave.setEnabled(true);
    }//GEN-LAST:event_jBtnGenderCreateActionPerformed

    private void jBtnGenderRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenderRefreshActionPerformed
        try {
            // TODO add your handling code here:
            populateGenders();
            placeGenders();
            jBtnGenderCreate.setEnabled(true);
            jBtnGenderEdit.setEnabled(false);
            jBtnGenderSave.setEnabled(false);
            clearGenderFields();
            setGenderFieldsEditable(false);
        } catch (SQLException ex) {
            Logger.getLogger(GendersForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (EntityExistsException ex) {
            Logger.getLogger(GendersForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(GendersForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(GendersForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransactionRequiredException ex) {
            Logger.getLogger(GendersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnGenderRefreshActionPerformed

    private void jBtnGenderCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenderCancelActionPerformed
        jBtnGenderCreate.setEnabled(true);
        jBtnGenderEdit.setEnabled(false);
        jBtnGenderSave.setEnabled(false);
        clearGenderFields();
        setGenderFieldsEditable(false);
    }//GEN-LAST:event_jBtnGenderCancelActionPerformed

    private void jBtnGenderEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenderEditActionPerformed
        // TODO add your handling code here:
        if (jTblGenders.getSelectedRowCount() == 1) {
            int index = jTblGenders.getSelectedRow();
            GenderTableModel d = ((GenderTableModel) jTblGenders.getModel());
            currentGender = d.getSelectedRow(index);
            placeGenderObjectToFields();
            setGenderFieldsEditable(true);
            jBtnGenderCreate.setEnabled(false);
            jBtnGenderSave.setEnabled(true);
            jBtnGenderEdit.setEnabled(false);
            genderInsertFlag = false;
        }
    }//GEN-LAST:event_jBtnGenderEditActionPerformed

    private void jBtnGenderSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenderSaveActionPerformed
        // TODO add your handling code here:
        populateGenderObject();

        boolean res = false;
        try {
            if (genderInsertFlag) {
                res = gef.create( currentGender);

            } else {
                res = gef.update(currentGender);
            }
            setGenderFieldsEditable(false);
            clearGenderFields();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        if (res) {
            try {
                jBtnGenderCreate.setEnabled(true);
                jBtnGenderEdit.setEnabled(false);
                jBtnGenderSave.setEnabled(false);
                populateGenders();
                placeGenders();
                 
            } catch (SQLException | EntityExistsException | IllegalStateException | IllegalArgumentException | TransactionRequiredException ex) {
                Logger.getLogger(GendersForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jBtnGenderSaveActionPerformed

     private void clearGenderFields(){
         jTfTitle.setText("");
         jTaDescription.setText("");
         jChkBStatus.setSelected(true);
     }

     private void setGenderFieldsEditable(boolean flag){
         jTfTitle.setEditable(flag);
         jTaDescription.setEditable(flag);
         jChkBStatus.setSelected(flag);
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGenderCancel;
    private javax.swing.JButton jBtnGenderCreate;
    private javax.swing.JButton jBtnGenderEdit;
    private javax.swing.JButton jBtnGenderRefresh;
    private javax.swing.JButton jBtnGenderSave;
    private javax.swing.JCheckBox jChkBStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTaDescription;
    private javax.swing.JTable jTblGenders;
    private javax.swing.JTextField jTfTitle;
    // End of variables declaration//GEN-END:variables

    private void placeGenderObjectToFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void populateGenders() throws EntityExistsException, 
            IllegalStateException, IllegalArgumentException, 
            TransactionRequiredException, SQLException {
       mGenders = gef.reads();
    }

    private void placeGenders() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void populateGenderObject() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
