/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealer;

import cardealer.database.EmployeesEntityFacade;
import cardealer.database.User_InfoEntityFacade;
import cardealer.database.exceptions.EntityExistsException;
import cardealer.models.Employee;
import cardealer.models.User_info;
import cardealer.tableModels.User_infoTableModel;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.transaction.TransactionRequiredException;

/**
 *
 * @author ahmet
 */
public class ManagementForm extends javax.swing.JFrame {

    private ArrayList<User_info> mUsers;
    private User_InfoEntityFacade uief;
    private User_info currentUser;
    private ArrayList<Employee> mEmployees;
    private EmployeesEntityFacade eef;
    private Employee currentEmployee;
    private User_info currentUserInfo;
    private boolean userinfoInsertFlag;

    /**
     * Creates new form Management
     */
    public ManagementForm() {
        initComponents();
        eef = new EmployeesEntityFacade();
        uief = new User_InfoEntityFacade();
        mUsers = new ArrayList<>();
        mEmployees = new ArrayList();
        currentUser = new User_info();
        currentEmployee = new Employee();
        try {
            populateEmployees();
            populateUsers();
            placeUsers();

        } catch (EntityExistsException | IllegalArgumentException | IllegalStateException | SQLException | TransactionRequiredException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void populateEmployees() throws EntityExistsException, IllegalStateException,
            IllegalArgumentException, TransactionRequiredException, SQLException {
        mEmployees = eef.reads();
    }

    private void populateUsers() throws EntityExistsException, IllegalStateException,
            IllegalArgumentException, TransactionRequiredException, SQLException {
        mUsers = uief.reads();
    }

    private void placeUsers() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblUserInfos = new javax.swing.JTable();
        jBtnUserInfoCreate = new javax.swing.JButton();
        jBtnUserInfoEdit = new javax.swing.JButton();
        jBtnUserInfoSave = new javax.swing.JButton();
        jBtnUserInfoShtyp = new javax.swing.JButton();
        jBtnUserInfoCancel = new javax.swing.JButton();
        jBtnUserInfoRefresh = new javax.swing.JButton();
        jTfUserInfoEmail = new javax.swing.JTextField();
        jPwUserInfoPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jCmbUserInfoEmployees = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jChkBUserInfoStatus = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblUserInfos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblUserInfos);

        jBtnUserInfoCreate.setText("Shto");
        jBtnUserInfoCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserInfoCreateActionPerformed(evt);
            }
        });

        jBtnUserInfoEdit.setText("Redakto");
        jBtnUserInfoEdit.setEnabled(false);
        jBtnUserInfoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserInfoEditActionPerformed(evt);
            }
        });

        jBtnUserInfoSave.setText("Ruaj");
        jBtnUserInfoSave.setEnabled(false);
        jBtnUserInfoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserInfoSaveActionPerformed(evt);
            }
        });

        jBtnUserInfoShtyp.setText("Shtyp");
        jBtnUserInfoShtyp.setToolTipText("E shtyp listën e veturave");
        jBtnUserInfoShtyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserInfoShtypActionPerformed(evt);
            }
        });

        jBtnUserInfoCancel.setText("Anulo");
        jBtnUserInfoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserInfoCancelActionPerformed(evt);
            }
        });

        jBtnUserInfoRefresh.setText("Rifresko");
        jBtnUserInfoRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUserInfoRefreshActionPerformed(evt);
            }
        });

        jTfUserInfoEmail.setText("jTextField1");

        jPwUserInfoPassword.setText("jPasswordField1");

        jLabel1.setText("Posta elektronike: ");

      
        jLabel2.setText("Fjalëkalimi: ");

        jLabel3.setText("Punëtori: ");

        jChkBUserInfoStatus.setText("Aktiv");

        jLabel4.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbUserInfoEmployees, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTfUserInfoEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jChkBUserInfoStatus)
                                    .addComponent(jPwUserInfoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnUserInfoCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnUserInfoEdit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnUserInfoRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnUserInfoCancel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnUserInfoSave)
                            .addComponent(jBtnUserInfoShtyp))
                        .addGap(0, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbUserInfoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfUserInfoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwUserInfoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBUserInfoStatus)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUserInfoCreate)
                    .addComponent(jBtnUserInfoEdit)
                    .addComponent(jBtnUserInfoSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnUserInfoRefresh)
                    .addComponent(jBtnUserInfoCancel)
                    .addComponent(jBtnUserInfoShtyp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnUserInfoCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserInfoCreateActionPerformed
        // TODO add your handling code here:
        clearUserInfoFields();
        setUserInfoFieldsEditable(true);
        userinfoInsertFlag = true;
        jCmbUserInfoEmployees.requestFocus();
        jBtnUserInfoCreate.setEnabled(false);
        jBtnUserInfoSave.setEnabled(true);
    }//GEN-LAST:event_jBtnUserInfoCreateActionPerformed

    private void jBtnUserInfoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserInfoEditActionPerformed
        // TODO add your handling code here:
        if (jTblUserInfos.getSelectedRowCount() == 1) {
            int index = jTblUserInfos.getSelectedRow();
            User_infoTableModel d = ((User_infoTableModel) jTblUserInfos.getModel());
            currentUser = d.getSelectedRow(index);
            placeUserInfoObjectToFields();
            setUserInfoFieldsEditable(true);
            jBtnUserInfoCreate.setEnabled(false);
            jBtnUserInfoSave.setEnabled(true);
            jBtnUserInfoEdit.setEnabled(false);
            userinfoInsertFlag = false;
        }
    }//GEN-LAST:event_jBtnUserInfoEditActionPerformed

    private void jBtnUserInfoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserInfoSaveActionPerformed
        // TODO add your handling code here:
        populateUserInfoObject();
        boolean res = false;
        try {
            if (userinfoInsertFlag) {
                res = uief.create(currentUserInfo);

            } else {
                res = uief.update(currentUserInfo);
            }
            setUserInfoFieldsEditable(false);
            clearUserInfoFields();

            if (res) {

                jBtnUserInfoCreate.setEnabled(true);
                jBtnUserInfoEdit.setEnabled(false);
                jBtnUserInfoSave.setEnabled(false);
                try {
                    populateUsers();
                    placeUsers();
                } catch (EntityExistsException | IllegalArgumentException | IllegalStateException | SQLException | TransactionRequiredException ex) {
                    System.out.println(ex.getMessage());
                }

            }

        } catch (SQLException
                | EntityExistsException | IllegalStateException | IllegalArgumentException | TransactionRequiredException ex) {
            System.out.println(ex.getMessage());
            Logger.getLogger(ManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnUserInfoSaveActionPerformed

    private void jBtnUserInfoShtypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserInfoShtypActionPerformed
        try {
            // TODO add your handling code here:
            MessageFormat header = new MessageFormat("Lista e veturave");
            MessageFormat footer = new MessageFormat("Faqja {0,number,integer}");

            jTblUserInfos.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(ManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnUserInfoShtypActionPerformed

    private void jBtnUserInfoCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserInfoCancelActionPerformed
        jBtnUserInfoCreate.setEnabled(true);
        jBtnUserInfoEdit.setEnabled(false);
        jBtnUserInfoSave.setEnabled(false);
        clearUserInfoFields();
        setUserInfoFieldsEditable(false);
    }//GEN-LAST:event_jBtnUserInfoCancelActionPerformed

    private void jBtnUserInfoRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUserInfoRefreshActionPerformed
        try {
            // TODO add your handling code here:
            populateUsers();
            placeUsers();
            jBtnUserInfoCreate.setEnabled(true);
            jBtnUserInfoEdit.setEnabled(false);
            jBtnUserInfoSave.setEnabled(false);
            clearUserInfoFields();
            setUserInfoFieldsEditable(false);
        } catch (Exception ex) {
            Logger.getLogger(ManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnUserInfoRefreshActionPerformed

    private void placeUserInfoObjectToFields() {
        this.jCmbUserInfoEmployees.setSelectedItem(currentUser.getEmployeeID());
        this.jTfUserInfoEmail.setText(currentUser.getEmail());
        this.jPwUserInfoPassword.setText(currentUser.getPassword());
        this.jChkBUserInfoStatus.setSelected(currentUser.isStatus());
    }

    private void setUserInfoFieldsEditable(boolean b) {
        this.jCmbUserInfoEmployees.setEnabled(b);
        this.jTfUserInfoEmail.setEditable(b);
        this.jPwUserInfoPassword.setEnabled(b);
        this.jChkBUserInfoStatus.setEnabled(b);
    }

    private void clearUserInfoFields() {
        this.jCmbUserInfoEmployees.setSelectedIndex(-1);
        this.jTfUserInfoEmail.setText("");
        this.jPwUserInfoPassword.setText("");
        this.jChkBUserInfoStatus.setText("");
    }

    private void populateUserInfoObject() {
        this.currentUser.setEmployeeID((Employee) jCmbUserInfoEmployees.getSelectedItem());
        this.currentUser.setEmail(jTfUserInfoEmail.getText());
        this.currentUser.setPassword(new String(jPwUserInfoPassword.getPassword()));
        this.currentUser.setStatus(jChkBUserInfoStatus.isSelected());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnUserInfoCancel;
    private javax.swing.JButton jBtnUserInfoCreate;
    private javax.swing.JButton jBtnUserInfoEdit;
    private javax.swing.JButton jBtnUserInfoRefresh;
    private javax.swing.JButton jBtnUserInfoSave;
    private javax.swing.JButton jBtnUserInfoShtyp;
    private javax.swing.JCheckBox jChkBUserInfoStatus;
    private javax.swing.JComboBox<Employee> jCmbUserInfoEmployees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPwUserInfoPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblUserInfos;
    private javax.swing.JTextField jTfUserInfoEmail;
    // End of variables declaration//GEN-END:variables

}
