/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealer;

import cardealer.database.Database;
import cardealer.database.SalesForecastsEntityFacade;

import cardealer.models.SaleForecast;
import cardealer.tableModels.SaleForecastTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Properties;

/**
 *
 * @author ahmet
 */
public class SalesForecastForm extends javax.swing.JFrame {

    private SaleForecast currentSaleForecast;
    private boolean salesForecastInsertFlag;
    private ArrayList<SaleForecast> mSalesForecasts;
    private SalesForecastsEntityFacade sfef;
    private static Properties props;

    /**
     * Creates new form SalesForecast
     */
    public SalesForecastForm() {
        initComponents();
        currentSaleForecast = new SaleForecast();
        salesForecastInsertFlag = false;
        mSalesForecasts = new ArrayList<>();
        sfef = new SalesForecastsEntityFacade();
        jTblSalesForecast.setModel(new SaleForecastTableModel());

        try {
            Path workingDirectory = Paths.get("").toAbsolutePath();
            String path = workingDirectory + "\\build\\classes\\cardealer\\config\\config.ini";
            final String dir = System.getProperty("user.dir");

            File f = new File(path);
            if (f.exists()) {
                System.out.println("current dir = " + dir);
                props = new Properties();
                props.load(new FileInputStream(path));
                // TODO code application logic here
                System.out.println("Trying to connect");
                CarForm.db = new Database();
                System.out.println("Connected");
                sfef = new SalesForecastsEntityFacade();
                mSalesForecasts = new ArrayList<>();
                currentSaleForecast = new SaleForecast();
                populateSalesForecast();
               
                
               
                
                this.pack();
            }
        } catch (IOException | SQLException ex) {
            System.out.println(ex.getMessage());
        }

        jTblSalesForecast.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (jTblSalesForecast.getSelectedRowCount() == 1) {
                    jBtnSaleForecastEdit.setEnabled(true);
                } else {
                    jBtnSaleForecastEdit.setEnabled(false);
                }

            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSalesForecast = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnSaleForecastCreate = new javax.swing.JButton();
        jBtnSaleForecastEdit = new javax.swing.JButton();
        jBtnSaleForecastSave = new javax.swing.JButton();
        jBtnSaleForecastRefresh = new javax.swing.JButton();
        jBtnSaleForecastCancel = new javax.swing.JButton();
        jCmbMonths = new javax.swing.JComboBox<>();
        jTFYear = new javax.swing.JTextField();
        jTfForecastSale = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTfRealization = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblSalesForecast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblSalesForecast);

        jLabel1.setText("Bërja:");

        jLabel3.setText("Viti:");

        jBtnSaleForecastCreate.setText("Shto");
        jBtnSaleForecastCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastCreateActionPerformed(evt);
            }
        });

        jBtnSaleForecastEdit.setText("Redakto");
        jBtnSaleForecastEdit.setEnabled(false);
        jBtnSaleForecastEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastEditActionPerformed(evt);
            }
        });

        jBtnSaleForecastSave.setText("Ruaj");
        jBtnSaleForecastSave.setEnabled(false);
        jBtnSaleForecastSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastSaveActionPerformed(evt);
            }
        });

        jBtnSaleForecastRefresh.setText("Rifresko");
        jBtnSaleForecastRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastRefreshActionPerformed(evt);
            }
        });

        jBtnSaleForecastCancel.setText("Anulo");
        jBtnSaleForecastCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastCancelActionPerformed(evt);
            }
        });

        jCmbMonths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel4.setText("Parashikimi i shitjes:");

        jLabel5.setText("Realizimi i shitjes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFYear)
                    .addComponent(jTfForecastSale, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jTfRealization, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jCmbMonths, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSaleForecastCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSaleForecastEdit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSaleForecastRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSaleForecastCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSaleForecastSave)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCmbMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTfForecastSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTfRealization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSaleForecastCreate)
                            .addComponent(jBtnSaleForecastEdit)
                            .addComponent(jBtnSaleForecastSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSaleForecastRefresh)
                            .addComponent(jBtnSaleForecastCancel))))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaleForecastCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaleForecastCreateActionPerformed

    private void jBtnSaleForecastEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaleForecastEditActionPerformed

    private void jBtnSaleForecastSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaleForecastSaveActionPerformed

    private void jBtnSaleForecastRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaleForecastRefreshActionPerformed

    private void jBtnSaleForecastCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSaleForecastCancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaleForecastCancel;
    private javax.swing.JButton jBtnSaleForecastCreate;
    private javax.swing.JButton jBtnSaleForecastEdit;
    private javax.swing.JButton jBtnSaleForecastRefresh;
    private javax.swing.JButton jBtnSaleForecastSave;
    private javax.swing.JComboBox<String> jCmbMonths;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFYear;
    private javax.swing.JTable jTblSalesForecast;
    private javax.swing.JTextField jTfForecastSale;
    private javax.swing.JTextField jTfRealization;
    // End of variables declaration//GEN-END:variables

    private void populateSalesForecast() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    private void clearSaleForecastFields() {
        jCmbMonths.setSelectedIndex(0);
        jTFYear.setText("");
        jTfForecastSale.setText("");
        jTfRealization.setText("");
    }

    private void setSaleForecastFieldsEditable(boolean b) {
       jCmbMonths.setEditable(b);
        jTFYear .setEditable(b);
        jTfForecastSale.setEditable(b);
        jTfRealization.setEditable(b);
    }

    private void placeSaleForecastObjectToFields() {
         jCmbMonths.setSelectedIndex(currentSaleForecast.getSelected_month()-1);
        jTFYear.setText(""+currentSaleForecast.getSelected_year());
        jTfForecastSale.setText(""+currentSaleForecast.getIdSaleForecast());
        jTfRealization.setText(""+currentSaleForecast.getRealization());
    }

    private void populateSaleForecastObject() {
        currentSaleForecast.setSelected_month((int)jCmbMonths.getSelectedItem());
        currentSaleForecast.setSelected_year(Integer.parseInt(jTFYear.getText()));
        currentSaleForecast.setForecastedSale(Integer.parseInt(jTfForecastSale.getText()));
        currentSaleForecast.setRealization(Integer.parseInt(jTfRealization.getText()));
    }

    private void placeSaleForecastbjectToFields() {
        
    }
}
