/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardealer;

import cardealer.database.SalesForecastsEntityFacade;
import cardealer.database.Database;
import cardealer.database.exceptions.EntityExistsException;
import cardealer.models.SaleForecast;
import cardealer.models.SaleForecast;
import cardealer.tableModels.SaleForecastTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.transaction.TransactionRequiredException;

/**
 *
 * @author ahmet
 */
public class SalesForecastForm extends javax.swing.JFrame {
    public static Database db;
    public static Properties props;
    private static SalesForecastsEntityFacade scsfrcef;
    private static ArrayList<SaleForecast> mSaleForecasts;
    private static SaleForecast currentSaleForecast;
    private static final Logger LOG = Logger.getLogger(SalesForecastForm.class.getName());
    private boolean carInsertFlag = false;
    /**
     * Creates new form SalesForecast
     */
    public SalesForecastForm() {
        initComponents();
        jTblSalesForecast.setModel(new SaleForecastTableModel());
        try {
            Path workingDirectory = Paths.get("").toAbsolutePath();
            String path = workingDirectory + "\\build\\classes\\cardealer\\config\\config.ini";
            final String dir = System.getProperty("user.dir");

            File f = new File(path);
            if (f.exists()) {
                System.out.println("current dir = " + dir);
                props = new Properties();
                props.load(new FileInputStream(path));
                // TODO code application logic here
                System.out.println("Trying to connect");
                SalesForecastForm.db = new Database();
                System.out.println("Connected");
                scsfrcef = new SalesForecastsEntityFacade ();
                mSaleForecasts = new ArrayList<>();
                currentSaleForecast = new SaleForecast();
                populateSaleForecasts();
                setVisible(true);
            }
        } catch (IOException | SQLException ex) {
            System.out.println(ex.getMessage());
        }
 
        jTblSalesForecast.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (jTblSalesForecast.getSelectedRowCount() == 1) {
                    jBtnSaleForecastEdit.setEnabled(true);
                } else {
                    jBtnSaleForecastEdit.setEnabled(false);
                }

            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblSalesForecast = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
         
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
         
        jBtnSaleForecastCreate = new javax.swing.JButton();
        jBtnSaleForecastEdit = new javax.swing.JButton();
        jBtnSaleForecastSave = new javax.swing.JButton();
        jBtnSaleForecastRefresh = new javax.swing.JButton();
        jBtnSaleForecastCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTblSalesForecast.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblSalesForecast);

        jLabel1.setText("Bërja:");

     
        jLabel2.setText("Viti i prodhimit:");

        jLabel3.setText("Modeli:");

         
        jBtnSaleForecastCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreateActionPerformed(evt);
            }
        });

        jBtnSaleForecastEdit.setText("Redakto");
        jBtnSaleForecastEdit.setEnabled(false);
        jBtnSaleForecastEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });

        jBtnSaleForecastSave.setText("Ruaj");
        jBtnSaleForecastSave.setEnabled(false);
        jBtnSaleForecastSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastSaveActionPerformed(evt);
            }
        });

        jBtnSaleForecastRefresh.setText("Rifresko");
        jBtnSaleForecastRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastRefreshActionPerformed(evt);
            }
        });

        jBtnSaleForecastCancel.setText("Anulo");
        jBtnSaleForecastCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaleForecastCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSaleForecastCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnSaleForecastEdit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtnSaleForecastRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSaleForecastCancel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSaleForecastSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                           
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSaleForecastCreate)
                            .addComponent(jBtnSaleForecastEdit)
                            .addComponent(jBtnSaleForecastSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnSaleForecastRefresh)
                            .addComponent(jBtnSaleForecastCancel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   
                    .addComponent(jLabel2))
                .addContainerGap(77, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jBtnCreateActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        clearSaleForecastFields();
        setSaleForecastFieldsEditable(true);
        carInsertFlag = true;
        jBtnSaleForecastCreate.setEnabled(false);
        jBtnSaleForecastSave.setEnabled(true);
    }                                          

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (jTblSalesForecast.getSelectedRowCount() == 1) {
            int index = jTblSalesForecast.getSelectedRow();
            SaleForecastTableModel d = ((SaleForecastTableModel) jTblSalesForecast.getModel());
            currentSaleForecast = d.getSelectedRow(index);
            placeSaleForecastbjectToFields();
            setSaleForecastFieldsEditable(true);
            jBtnSaleForecastCreate.setEnabled(false);
            jBtnSaleForecastSave.setEnabled(true);
            jBtnSaleForecastEdit.setEnabled(false);
            carInsertFlag = false;
        }
    }

   
    private void jBtnSaleForecastCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastCreateActionPerformed
        // TODO add your handling code here:
        clearSaleForecastFields();
        setSaleForecastFieldsEditable(true);
        carInsertFlag = true;
        jBtnSaleForecastCreate.setEnabled(false);
        jBtnSaleForecastSave.setEnabled(true);
    }//GEN-LAST:event_jBtnSaleForecastCreateActionPerformed

    private void jBtnSaleForecastEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastEditActionPerformed
        // TODO add your handling code here:
        if (jTblSalesForecast.getSelectedRowCount() == 1) {
            int index = jTblSalesForecast.getSelectedRow();
            SaleForecastTableModel d = ((SaleForecastTableModel) jTblSalesForecast.getModel());
            currentSaleForecast = d.getSelectedRow(index);
            placeSaleForecastObjectToFields();
            setSaleForecastFieldsEditable(true);
            jBtnSaleForecastCreate.setEnabled(false);
            jBtnSaleForecastSave.setEnabled(true);
            jBtnSaleForecastEdit.setEnabled(false);
            carInsertFlag = false;
        }
    }//GEN-LAST:event_jBtnSaleForecastEditActionPerformed

    private void jBtnSaleForecastSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastSaveActionPerformed
        // TODO add your handling code here:
        populateSaleForecastObject();
        boolean res = false;
        try {
            if (carInsertFlag) {
                res = scsfrcef.create(currentSaleForecast);

            } else {
                res = scsfrcef.update(currentSaleForecast);
            }
            setSaleForecastFieldsEditable(false);
            clearSaleForecastFields();

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        if (res) {
            jBtnSaleForecastCreate.setEnabled(true);
            jBtnSaleForecastEdit.setEnabled(false);
            jBtnSaleForecastSave.setEnabled(false);
            populateSaleForecasts();

        }
    }//GEN-LAST:event_jBtnSaleForecastSaveActionPerformed

    private void jBtnSaleForecastRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastRefreshActionPerformed
        // TODO add your handling code here:
        populateSaleForecasts();
    }//GEN-LAST:event_jBtnSaleForecastRefreshActionPerformed

    private void jBtnSaleForecastCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaleForecastCancelActionPerformed
        jBtnSaleForecastCreate.setEnabled(true);
        jBtnSaleForecastEdit.setEnabled(false);
        jBtnSaleForecastSave.setEnabled(false);
        clearSaleForecastFields();
        setSaleForecastFieldsEditable(false);
    }//GEN-LAST:event_jBtnSaleForecastCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSaleForecastCancel;
    private javax.swing.JButton jBtnSaleForecastCreate;
    private javax.swing.JButton jBtnSaleForecastEdit;
    private javax.swing.JButton jBtnSaleForecastRefresh;
    private javax.swing.JButton jBtnSaleForecastSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblSalesForecast;
    // End of variables declaration//GEN-END:variables

    private void populateSaleForecasts()  {
        try {
            mSaleForecasts= scsfrcef.reads();
        } catch (EntityExistsException | IllegalStateException | 
                IllegalArgumentException | TransactionRequiredException | 
                SQLException ex) {
            Logger.getLogger(SalesForecastForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearSaleForecastFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setSaleForecastFieldsEditable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void placeSaleForecastObjectToFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void populateSaleForecastObject() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void placeSaleForecastbjectToFields() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
